2023-06-06 18:23:05,797 INFO    MainThread:11792 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-06-06 18:23:05,797 INFO    MainThread:11792 [wandb_setup.py:_flush():76] Configure stats pid to 11792
2023-06-06 18:23:05,797 INFO    MainThread:11792 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Neko\.config\wandb\settings
2023-06-06 18:23:05,797 INFO    MainThread:11792 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Neko\OneDrive\Desktop\learning\Homework\mlops_zoomcamp\experiment-tracking\wnb\wandb\settings
2023-06-06 18:23:05,797 INFO    MainThread:11792 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-06 18:23:05,797 INFO    MainThread:11792 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-06 18:23:05,799 INFO    MainThread:11792 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'experiment-tracking\\wnb\\preprocess_data.py', 'program': 'C:\\Users\\Neko\\OneDrive\\Desktop\\learning\\Homework\\mlops_zoomcamp\\experiment-tracking\\wnb\\preprocess_data.py'}
2023-06-06 18:23:05,799 INFO    MainThread:11792 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\Neko\OneDrive\Desktop\learning\Homework\mlops_zoomcamp\experiment-tracking\wnb\wandb\run-20230606_182305-mddlms4k\logs\debug.log
2023-06-06 18:23:05,799 INFO    MainThread:11792 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\Neko\OneDrive\Desktop\learning\Homework\mlops_zoomcamp\experiment-tracking\wnb\wandb\run-20230606_182305-mddlms4k\logs\debug-internal.log
2023-06-06 18:23:05,799 INFO    MainThread:11792 [wandb_init.py:init():547] calling init triggers
2023-06-06 18:23:05,799 INFO    MainThread:11792 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-06-06 18:23:05,799 INFO    MainThread:11792 [wandb_init.py:init():596] starting backend
2023-06-06 18:23:05,799 INFO    MainThread:11792 [wandb_init.py:init():600] setting up manager
2023-06-06 18:23:05,806 INFO    MainThread:11792 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-06-06 18:23:05,812 INFO    MainThread:11792 [wandb_init.py:init():606] backend started and connected
2023-06-06 18:23:05,816 INFO    MainThread:11792 [wandb_init.py:init():700] updated telemetry
2023-06-06 18:23:05,862 INFO    MainThread:11792 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-06-06 18:23:05,948 ERROR   MainThread:11792 [wandb_init.py:init():763] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-06-06 18:23:06,179 ERROR   MainThread:11792 [wandb_init.py:init():1168] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "C:\Users\Neko\OneDrive\Desktop\learning\Homework\mlops_zoomcamp\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
  File "C:\Users\Neko\OneDrive\Desktop\learning\Homework\mlops_zoomcamp\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-06-06 18:23:07,192 WARNING MsgRouterThr:11792 [router.py:message_loop():77] message_loop has been closed
